name: pvpswap
main: com.ProgramTurtle.pvpswap
version: 1.1.0
author: ProgramTurtle
commands:
   Join:
         description: Join a PvPSwap arena!
         usage: /pjoin [arena]
   Leave:
         description: Leave a PvPSwap arena
         usage: /pleave
   
